### ISSUE TITLE
Frame count

### ISSUE THREAD

**Issue by fazolin** [rsodre/AeroplaneC4D#1]
I believe that the plugin interferes with the manual input of the amount of frames in the animation, not allowing the input of values ​​by keyboard, only via mouse. I tested on r20 on win and macosx and the same bug occurred. If there is no correlation, please delete the issue.

**Comment by rsodre** [comment]
Seems like you're right.
Weird, will try to find out why...

**Comment by rsodre** [comment]
Fixed on Release 1.1
